% generate_ascii_catalog: generates ASCII catalog of results of DLA
% search

catalog = load(sprintf('%s/zqso_only_catalog', processed_directory(release)));

% load(sprintf('%s/dla_samples',       processed_directory(training_release)));
% load the processed file; the filename here is the file on the Google Drive
% http://tiny.cc/gp_zestimation_catalogue
load(sprintf('%s/processed_zqso_only_qsos_%s-%s_uniformprior', ...
    processed_directory(release), ...
    test_set_name, optTag));

% write your samples into .data file
fid = fopen(sprintf('%s/%s_zqsos_samples.dat',      ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

for i = 1:numel(offset_samples_qso)
  fprintf(fid, '%06f\n', ...
          offset_samples_qso(i));
end

fclose(fid);

% write matlab catalogue into ascii file
fid = fopen(sprintf('%s/%s_spectra.dat',          ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

for i = 1:numel(catalog.z_qsos)
  fprintf(fid, ...
          '%09i %-18s %04i %05i %04i %011.7f %+011.7f %06.4f %08.4f %i%i%i%i%i\n', ...
          catalog.thing_ids(i),               ...
          deblank(catalog.sdss_names{i}),     ...
          catalog.plates(i),                  ...
          catalog.mjds(i),                    ...
          catalog.fiber_ids(i),               ...
          catalog.ras(i),                     ...
          catalog.decs(i),                    ...
          catalog.z_qsos(i),                  ...
          catalog.snrs(i),                    ...
          bitget(catalog.filter_flags(i), 1), ...
          bitget(catalog.filter_flags(i), 2), ...
          bitget(catalog.filter_flags(i), 3), ...
          bitget(catalog.filter_flags(i), 4), ...
          bitget(catalog.filter_flags(i), 5)  ...
          );
end

fclose(fid);

% write your zqsos inference results
fid = fopen(sprintf('%s/%s_results.dat',          ...
                    processed_directory(release), ...
                    test_set_name),               ...
            'w');

searched_ind = find(test_ind);

for i = 1:numel(searched_ind)
  catalog_ind = searched_ind(i);
  fprintf(fid, '%09i %-18s ', catalog.thing_ids(catalog_ind));

  fprintf(fid, ...
          '%06.4f %06.4f\n', ...
          z_map(i),             ...
          z_true(i)             ...
          );
end

fclose(fid);
